#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppInventory.Resource", IsApplication=true)]

namespace AppInventory
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int ListViewHighlighted = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int ListViewSelected = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int boxp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int boxpS = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int btnClean = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int btnExport = 2131165193;
			
			// aapt resource value: 0x7f070010
			public const int btnInserir = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int btnNovo = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int chkBusca = 2131165202;
			
			// aapt resource value: 0x7f070006
			public const int imgLogo = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int lblPartnumber = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int lblQtd = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int lblUltLido = 2131165198;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout2 = 2131165188;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout3 = 2131165199;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout4 = 2131165189;
			
			// aapt resource value: 0x7f070013
			public const int lvDados = 2131165203;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int textView2 = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int txtPartNumber = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int txtPartNumberHide = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int txtQtd = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int txtVItem = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int txtVQtd = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListViewLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
